### ISSUE TITLE
Knitr chunk header is "old-style"

### ISSUE THREAD

**Issue by nucholab** [chasberry/orgmode-accessories#14]
These days =knitr= works fine by opening the chunks with say,

\`\`\`{bash}

 or

\`\`\`{python}

without having to do ```{r  engine="python"}``` or some such.

**Comment by chasberry** [comment]
Thanks. I was aware of that possibility. 

But `engine` is still a valid chunk option and that stuff is all under the hood and out of sight of the user.

So unless that idiom is deprecated, I am inclined to leave things as they are.

**Comment by chasberry** [comment]
Now that quarto is released it made sense to update to the new style both for the engine and for the YAML style chunk options.

So now, with `org-ravel-engines` as `(("R") ("bash" . "engine='bash'"))`, a src block like

    #+name: demo-bash
    #+begin_src R :ravel engine='bash', echo = FALSE
    echo "Hello World"
    #+end_src

will export to `*.Rmd` like this:

    ```{bash}
    #| label: demo-bash
    #| echo: FALSE
    echo "Hello World"
    ```
The old style can be retained by following the directions in `ox-ravel.org` `*** org-ravel-style-x-md` just before the `org-ravel-style-x-md-old` src block.

--- 

Also, note that for compatibility with quarto, the `.Rmd` file extension that is produced by default can be changed to `.qmd` by customizing the entry for ~md~ in `org-ravel-style-alist`.
