### ISSUE TITLE
Link to image is not converted to proper image link in markdown file

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#15]
Hi
I have this code:
![image](https://user-images.githubusercontent.com/4311763/71520844-28026700-288c-11ea-9d66-80f052857551.png)

where I wanted to ignore the code but add a link to the generated image on the R markdown file. 
instead on the export I get:

> # images
> 
> [[file:```{r  eval=FALSE,echo=FALSE }
> qplot(rnorm(100)) 
> ```]]

I have a lot of images in the report and I don't want to have to evaluate all the image blocks everytime I render it. And besides want to see the image in the org file as well. So I would rather just use that image during rendering.

How can I accomplish this?

**Comment by chasberry** [comment]
Use this header arg:

```:eval never-export```

and you can omit the 

```:ravel eval=FALSE, echo=FALSE``` 

as nothing is exported.

When I try this with your code (albeit using `ggplot2::qplot`) I get a `*.Rmd` file that will render with the graph included.

**Comment by fkgruber** [comment]
Thanks that works.
Is there any way to change the name of the image.? By default it adds the caption img:

` ![img](./fig_test__0.png)`

tried adding name: and caption but didn't work


> #+name: test name
> #+caption: my cations is this
> #+BEGIN_SRC R  :results output graphics file :exports results :file ./fig_test__0.png :eval never-export :ravel eval=FALSE
> qplot(rnorm(100))
> #+END_SRC
>

**Comment by chasberry** [comment]
The `md` exporter on which the rmarkdown exporter is built does not handle captions in the manner you would like.  The `md` exporter is pretty bare bones and supposed to follow strict markdown conventions without extensions. 

Of course, you can hand-craft links to export such images with captions if you depend on `md` to handle them. Just wrap them in md export blocks or snippets.

You can use the `file-desc` header to add a caption, but that will not render as an inline image on the markdown side. You could pass the result to a `:post` src block to format it as a proper inline image in the markdown style, i.e. prepend a `!`, place the caption in brackets, and the file name in parentheses. Then use `:wrap export md` to protect it from further processing. Or you can add a filter to check links and prepend a `!` to any image links that do not have them. 

Honestly, I recommend letting the rmarkdown or knitr do such things. i.e. generate the graphics in `render()` and  have a `fig.cap` argument to label the graphics from the R chunk.

One of the reasons for writing `ox-ravel` was that letting `knitr` or `render` do the formatting and captioning seemed so much easier than figuring out how to get babel to do that and other things like caching long running computations and nicely formatting tables. 

If the time it takes to generate graphs is an issue, maybe you should cache them.  `knitr` and `render` handle caching pretty well.

**Comment by fkgruber** [comment]
thanks for all the suggestions!
I've been trying to use the cache=TRUE options but I often feel it is recalculating.  How does it know when to recalculate? Because I feel that I made a small change to some part of the orgfile, generated the new rmd file and when I render it often it just relcaulate everything even in parts that were not changed.  

What are the rules that can lead to it to redo the operations?

**Comment by chasberry** [comment]
See the knitr docs for this info, esp.  
[https://yihui.org/knitr/demo/cache/#more-granular-cache](url) and 
[https://yihui.org/knitr/options/#cache](url)

Also [https://stackoverflow.com/search?q=knitr+cache](url) will give you some tips.

FWIW, when I use caching, I generally set `cache=2`, specify no dependencies, and manually clear cache before doing a final run.  Also, I try to separate printing and formatting from big calculations so I can tweak them without triggering a cache reset. And I avoid changing `options()` as some of them reset cache (or used to?).

**Comment by fkgruber** [comment]
Thanks
this is very helpful.

I do like the idea of having the image and tables in the orgfile itself. For my own use it is usually good enough but when I want to show someone else then I rather render to the html rmarkdown file

**Comment by fkgruber** [comment]
> Thanks that works.
> Is there any way to change the name of the image.? By default it adds the caption img:
> 
> ` ![img](./fig_test__0.png)`
> 
> tried adding name: and caption but didn't work
> 
> > #+name: test name
> > #+caption: my cations is this
> > #+BEGIN_SRC R  :results output graphics file :exports results :file ./fig_test__0.png :eval never-export :ravel eval=FALSE
> > qplot(rnorm(100))
> > #+END_SRC

I love how it is working with :eval=FALSE. 

The only thing that is missing is a way to remove that img" caption. Is there a way to at least not have any caption? 

Currently, every image has the word img in it
![image](https://user-images.githubusercontent.com/4311763/78404640-d7a64e00-75cc-11ea-8cf5-7fc0a766e758.png)

**Comment by chasberry** [comment]
I really do not get the code in the src block you are showing. 

If you want a src block to produce a caption use the `fig.cap` code chunk option. And get rid of the `:results file`, which will break ravel exports. 

`demos.org` has some caption examples.

**Comment by fkgruber** [comment]
I'm currently using something like

```
#+BEGIN_SRC R :results output graphics file :exports results :file ./fig_test__0.png :eval never-export :ravel eval=FALSE
qplot(rnorm(100))
#+END_SRC
```

This allows me to have the image in the org file and in the ravel rmd export. I don't want any caption at all. However, I get the "img" caption by force. is there a way to replace "img" with "" so the caption is empty?

**Comment by chasberry** [comment]
This is tricky, but you can use computed header arguments to get what you want. 

Use `fig.cap=""` to force an empty caption.

```
#+header: :results (if org-export-current-backend "output" "graphics file" ) 
#+header: :file    (unless org-export-current-backend "./fig_test__0.png")
#+header: :ravel fig.cap = ""
#+BEGIN_SRC R 
qqnorm(rnorm(100))
#+END_SRC

```

**Comment by fkgruber** [comment]
this is not really doing what I had in mind, I still want to use :eval never-export so the existing image is used.

But in the Rmd file I would like to get

 `![](img/fig_condi_truenet.png)`

instead of 
` ![img](img/fig_condi_truenet.png)`

 what I'm doing right now is search and replace on the exported Rmd file and replacing [img] by []

**Comment by chasberry** [comment]
I am afraid that your response was garbled. 

Can you post the files you refer to somewhere, please?

When I click on the thumbnails, I get 'Not found'.

**Comment by fkgruber** [comment]
fixed it

**Comment by chasberry** [comment]
Thanks for fixing your earlier msg.

Do not use `:eval never-export` for any src block you want ravel to process.

The `![img][...]` output is not placed there by ravel. The markdown exporter from `ox-md` does that.

The results of R src blocks handled by ravel are removed from the copy buffer. And that includes file links.

With the example I posted, I can execute the src block and have the image inlined in the org buffer. When I subsequently export with Ravel-markdown the result I get is

<pre>
---
# YAML header created by ox-ravel
author: Charles Berry
---
```{r  fig.cap = "" }
qqnorm(rnorm(100)) 
```
</pre>

You can see what the result was - no reference to the image is included. 

When this is rendered by `markdown::render`, the image appears with no caption..

If the example I gave does not behave exactly as I described, let me know.

If you have image links you do not want ravel to touch, then it is up to you to deal with the markdown that `ox-md` produces. I do this myself (usually for screenshots) and add a filter to `org-export-filter-link-functions` to clear out the `img` that `ox-md` wants to add.

**Comment by fkgruber** [comment]
thanks for the clarification.  I think then that the solution that I'm looking for is adding the filter to org-export-filter-link-functions to clear out the img.  

I will take a look to see how that works. You don't happen to have the code that you use handy do you?

thank you very much

**Comment by chasberry** [comment]
I do have that code (see below).

If the issue you have in leaving `:eval never-export` is that you want to avoid lengthy computations, in the future you can use knitr's caching facility to save them.

Anyway:

```
#+begin_src emacs-lisp
  (defun org-ravel-md-filter-links (link backend info)
	 "Ensure \" \" are properly handled in Markdown export."
	  (when (org-export-derived-backend-p backend 'md)
	    (replace-regexp-in-string "!\\[img\\]" "![ ]" link nil t)))

  (add-to-list 'org-export-filter-link-functions
	       'org-ravel-md-filter-links)
#+end_src
```

**Comment by fkgruber** [comment]
thanks I will try that.

I also noticed something interesting.

If I add caption to the result block say:
![image](https://user-images.githubusercontent.com/4311763/78458898-ebac8700-7682-11ea-892f-159e78367766.png)
then if I export as using ravel-html option I get:
![image](https://user-images.githubusercontent.com/4311763/78458908-03840b00-7683-11ea-8dda-d1d2f8bf3732.png)


So the ravel-markdown is treating the links/caption differently.

**Comment by chasberry** [comment]
No. Ravel does nothing.

Evidently, you still have `:eval never-export` set.

You will get the same result with vanilla markdown export.

**Comment by fkgruber** [comment]
The code worked really well. thank you


> I do have that code (see below).
> 
> If the issue you have in leaving `:eval never-export` is that you want to avoid lengthy computations, in the future you can use knitr's caching facility to save them.
> 
> Anyway:
> 
> ```
> #+begin_src emacs-lisp
>   (defun org-ravel-md-filter-links (link backend info)
> 	 "Ensure \" \" are properly handled in Markdown export."
> 	  (when (org-export-derived-backend-p backend 'md)
> 	    (replace-regexp-in-string "!\\[img\\]" "![ ]" link nil t)))
> 
>   (add-to-list 'org-export-filter-link-functions
> 	       'org-ravel-md-filter-links)
> #+end_src
> ```

**Comment by fkgruber** [comment]
I found a simpler alternative
![[./myimag.png][My caption]]
correctly convert this to a rmarkdown image link with caption

**Comment by chasberry** [comment]
Wow! 

I wonder why I never got this before. If link processing in `ox-md.el` did not change this, I guess I missed it.

Thanks!
