### ISSUE TITLE
YAML front matter how to make it work?

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#17]
Hi,
Is there a specific orgmode configuration to get the yaml working? I'm using
#+BEGIN_EXPORT yaml
title:  test
output: html_document
author: me
#+END_EXPORT
and it just get ignored.

So far I've been using
#+begin_export md instead and adding the --- by hand.

**Comment by chasberry** [comment]
Are you using the latest commit in the org-9-plus branch? 

It is ```04abe205a918a5c2246c56180024a8a17237ef02```

When I run your example with ```C-c C-e r M``` I get 
```
---
# YAML header created by ox-ravel
title: test
output: html_document
author: me
author: Charles Berry
---
```
in the ```* ravel-markdown Output *``` buffer.

If `rmd-yaml` is `'footer` (by default) any non-nil values of `title`, `author`, and  `date` are added at the end of the YAML block (and override any previously defined),

Adding  ```#+OPTIONS: author:nil```  or ```#+OPTIONS: rmd_yaml:nil``` gives a similar result, but without the last ```author: Charles Berry``` line.

FWIW, I would set up my *.org file like this:

```
#+AUTHOR: me
#+TITLE: test

#+BEGIN_EXPORT yaml
output: html_document
#+END_EXPORT
```

with the result being 

```
---
# YAML header created by ox-ravel
output: html_document
title: test
author: me
---
```

**Comment by fkgruber** [comment]
There most be a yaml related configuration somewhere. I'm using
Org mode version 9.3.1 (9.3.1-elpaplus @ /Users/fred/.emacs.d/elpa/org-plus-contrib-20191230/)

created an orgfile having:

```
#+AUTHOR: me
#+TITLE: test
 
#+BEGIN_EXPORT yaml
output: html_document
#+END_EXPORT
** Section 1
 #+begin_src R
head(mtcars)
#+end_src
```


C-e r M gives me:

```
# Table of Contents

1.  [Section 1](#orgad11846)



<a id="orgad11846"></a>

# Section 1

```{r   }
head(mtcars) 
```

```

**Comment by chasberry** [comment]
Please update ```ox-ravel.el```  Older versions do not support YAML export blocks.

Be sure you have the ```'md``` backend loaded.

Verify that you have succeeded in updating ox-ravel.el and loaded it by typing 

```C-h f org-ravel--yaml-header RET```

If you get ```[No match]``` or any other error message then you did not succeed in updating ox-ravel.

If you get a docstring, then you should be able to process YAML export blocks.

**Comment by fkgruber** [comment]
Thanks that worked

**Comment by chasberry** [comment]
Great!
