### ISSUE TITLE
how to add CSS blocks?

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#18]
Hi 
I would like to include a css block in the exported R-markdown so the source blocks have scroll bars.

Essentially I would like to have (see https://bookdown.org/yihui/rmarkdown-cookbook/html-scroll.html) 
```{css, echo=FALSE}
pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 100px;
}
```

However adding 
#+begin_src css

  pre {
    max-height: 400px;
    overflow-y: auto;
  }

  pre[class] {
    max-height: 400px;
  }

#+end_src

becomes:
    pre {
      max-height: 400px;
      overflow-y: auto;
    }
    
    pre[class] {
      max-height: 400px;
    }

instead which does not do what I want.

 is there a way  around this?

or an alternative way to get scroll bar and control the size of the source code?

**Comment by chasberry** [comment]
I just added `css` to the engine selections. 

And I added your example as [https://github.com/chasberry/orgmode-accessories/blob/org-9-plus/scroll-markdown.org](url).

BTW, thanks for cluing me in to this nifty feature!

**Comment by fkgruber** [comment]
thanks!

**Comment by fkgruber** [comment]
by activating the css do you mean adding css to 
org-babel-do-load-languages?

**Comment by chasberry** [comment]
No. Customize org-ravel-engines. You can do `C-h v org-ravel-engines RET`, click `customize`, then check `css` and click `Apply` or `Apply and Save`.

**Comment by fkgruber** [comment]
perfect thanks
