### ISSUE TITLE
Exporting inline source code blocks in org 9.4

### ISSUE THREAD

**Issue by percyfal** [chasberry/orgmode-accessories#19]
Hi,

I think this issue is actually related to upstream changes going from org 9.3.8 to 9.4, but I thought I'd mention it here in case someone else reports similar issues. Upon changing to org9.4 source code blocks are exported with backticks and underscores escaped with backslash. A minimum working org file would be 

```
#+OPTIONS: ^:nil toc:nil -:nil
src_R{1+3}
src_R{is.numeric_version(package_version("0.0"))}
```
This exports as 
```
`r 1+3 `
`r is.numeric_version(package_version("0.0")) `
```
in org 9.3.8 but in org 9.4
```
\`r 1+3 \`
\`r is.numeric\_version(package\_version("0.0")) \`
```
I've setup my init file in a $HOME/tmp/.emacs.d directory, pointing the home directory here (`env HOME=$HOME/tmp emacs`) so that no personal customizations interfere, and linking ox-ravel.el to the elisp directory:
```
(add-to-list 'load-path "~/../opt/org-mode/lisp")
(add-to-list 'load-path "~/.emacs.d/elisp")
(require 'org)
(require 'ob-R)
(require 'ox-ravel)
(require 'ox-md)
(provide 'init)
```
I have managed to locate a difference in behaviour in the function `org-md-plain-text` which is called by `org-export-data`, but I'm not proficient enough an elisp programmer to figure out why; the text is transformed in `org-md-plain-text` in org9.4 but not in org9.3.8, presumably due to changes in the communcation channel? 

Anyhow I thought I'd post something in the orgmode mailing list but I wanted to rule out any issues with ox-ravel first.

BTW, ox-ravel is *great* - my work greatly depends on it! Thanks!

/P

**Comment by chasberry** [comment]
Thanks for your report and the compliment. 

`commit dc8f5ce2f18d0a57ab8570765b9edca1ccada98e` should have fixed this. 

Using the latest commit from the `org-9-plus` branch and the latest from org master (`9..4-31`) I get the desire output.

Please update `ox-ravel.el` and try again. If this didn't fix things re-open this issue, please

**Comment by percyfal** [comment]
Well do I feel silly! I had updated orgmode-accessories but I forgot to regenerate ox-ravel.el (doh!). Everything works as expected now - thanks! /P
