### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by slyrus** [chasberry/orgmode-accessories#21]
I'm very intrigued by the possibility of using org-mode as a replacement for Rmardown, ultimately feeding into pandoc. Is this project still active? Is what I describe supported currently? Thanks!

**Comment by chasberry** [comment]
I use org-mode to manage my R projects.  So I guess the answer is yes. The project is active although I make few changes to the code base in recent years as it works well for my purposes.

Most of the *.org files in the repository demonstrate capabilities.

In my own work, I often write in a *.org file, try out R code interactively, edit text as needed, then export via ox-ravel to either *.Rnw or *.Rmd and use knitr or rmarkdown to render the final version. Rinse and repeat.

**Comment by slyrus** [comment]
I guess I was hoping there was a way to skip the *.Rnw or *.Rmd export step. I guess what I _really_ want is a language agnostic alternative to rmarkdown::render that directly feeds into pandoc with output from embedded R code, shell code, etc... Perhaps rmarkdown::render can be made to handle these (or perhaps it does already for other languages as it does for R) and perhaps the export to Rmd isn't so bad. I'll keep exploring the .org files in the repo. Thanks again!

**Comment by chasberry** [comment]
Well, you can export from *.org directly with a variety of exporters with shell, awk, python, R, and a bunch of other language src blocks. You know the manual sections on [Exporting](https://orgmode.org/manual/Exporting.html#Exporting) and [Working-with-Source-Code](https://orgmode.org/manual/Working-with-Source-Code.html#Working-with-Source-Code), right?

You do not need padoc to do these exports. But if pandoc has some special advantage maybe [ox-pandoc](https://github.com/kawabata/ox-pandoc) helps.
