### ISSUE TITLE
How to properly use CACHE=TRUE

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#22]
Hi
I'm setting the cache=TRUE in the ravel options but it seems every time I generate the Rmd file it recalculate the cache blocks even if I haven't modified the cache block.

What triggers recalculating caching blocks? Does adding an empty line above triggers it? Is there a way to prevent this?

thanks
FKG

**Comment by chasberry** [comment]
If you have (say) `abc.Rmd` like

    ---
    # YAML header created by ox-ravel
    author: Charles Berry
    ---
    
    # cache this chunk
    
    ```{r  show-time, cache=TRUE }
    firstTime <- date()
    firstTime 
    ```

and render it with

```
R --slave --no-restore '-e rmarkdown::render("abc.Rmd")'
```

from the shell command line, you should get the same timestamp every time, but you should review 

[https://yihui.org/knitr/demo/cache/](url)

as a number of things can result in rebuilding the cache.
