### ISSUE TITLE
change 1 ravel header options keeping the rest of the global ones

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#23]
Hi
Currently it seems that if you change a :ravel option on a code block then the rest of the :ravel options specified globally are ignored. It would be better if we could only change specific options in the code block while keeping the rest of the global option. 
Isn't that how the org-babel options work?
FKG

**Comment by chasberry** [comment]
Not exactly. Babel headers usually have one arg. 

Each header is changed independently, so the issue usually doesn't arise.

`:ravel` is just another header with one arg.

(The `:results` header is an exception in that one can override a buffer wide setting for a single arg.)


In ox-ravel, to enable a chunk option to be set without resetting a chunk options set buffer wide, you can use

```
#+attr_ravel: echo=TRUE
```
just before a src block to override the `echo` option for just that chunk.  It does this by appending its value to the other chunk options and the last option overrides the earlier ones.

The use of `attr_ravel`  is illustrated in 

[https://raw.githubusercontent.com/chasberry/orgmode-accessories/org-9-plus/slidify-example.org](url)

**Comment by fkgruber** [comment]
thanks! that is useful
