### ISSUE TITLE
ox-ravel export clash with org-ref?

### ISSUE THREAD

**Issue by percyfal** [chasberry/orgmode-accessories#24]
Hi!

I have recently experienced problems with the exports when both ox-ravel and org-ref are loaded. For some reason, ox-ravel exports ignores export_file_name, but only if org-ref is loaded. The following .emacs and test.org reproduces the issue:

```
;; NB: modify locations of org-mode, ox-ravel and elpa packages as needed
;; org-mode source installation
(add-to-list 'load-path "~/src/org-mode/lisp")
(require 'org)
;; ox-ravel path
(add-to-list 'load-path "~/.emacs.d/elisp/")

;; elpa packages
(let ((base "~/.emacs.d/elpa"))
  (add-to-list 'load-path base)
  (dolist (f (directory-files base))
    (let ((name (concat base "/" f)))
      (when (and (file-directory-p name) 
                 (not (equal f ".."))
                 (not (equal f ".")))
        (add-to-list 'load-path name)))))

(require 'ox)
(require 'ox-md)
(require 'ox-ravel)
;; (require 'org-ref)
```
and with test.org
```
* Test
:PROPERTIES:
:EXPORT_FILE_NAME: tmp/test.md
:END:
foo

```
With the above setup, `C-c C-e C-s C-a r m` at heading exports to `tmp/test.md`, but if I include org-ref by uncommenting the last line in the init, it exports to `test.md`. Have you encountered this issue? I'm on org-mode 9.5.2, latest ox-ravel, and org-ref 3.0. I realize the issue may actually be with org-ref 3.0, but I have failed to isolate whatever is causing this behaviour. I have solved it by modifying the ox-ravel source such that a different menu key for  `org-export-define-derived-backend` (e.g. `?a`) is employed; would it be possible to customize this setting?

**Comment by chasberry** [comment]
I tried your example and confirm it's behavior. But it happens even if ox-ravel IS NOT required.

If you do not load ox-ravel, but load org-ref and try `C-c C-e C-s r m` with point on the headline below:

```
* Test
:PROPERTIES:
:EXPORT_FILE_NAME: xyz.md
:END:
foo
```

the file created is `test.md`

Looks like org-ref does not honor the `EXPORT_FILE_NAME` property.

---

I'll put allowing users to specify an alternate menu key on my TODO list.

**Comment by chasberry** [comment]
Customizing `org-ravel-menu-key` nows allows user to choose the menu key with the default still `?r`.

Note that setting the variable changes the menu the next time `ox-ravel` is loaded.
