### ISSUE TITLE
Only latex and html backends, not markdown, nor beamer.

### ISSUE THREAD

**Issue by acid-bbq** [chasberry/orgmode-accessories#27]
When I do `C-c C-e` I only have `ravel-html` and `ravel-latex`. Not `ravel-markdown`, nor `ravel-beamer`.

I've downloaded `ox-ravel.org`, opened it in Emacs, and did `M-x org-babel-tangle`. It created `ox-ravel.el`, then I load it with `(require 'ox-ravel)`.

Did I do something wrong? Or should I do something more for `markdown` and `beamer` to appear?

I use org mode 9.6.1 and Emacs 28.1.

**Comment by chasberry** [comment]
You have to add the parent backends either to your init file or with interactive commands.

For example, `M-x load-library ox-md` would do it interactively for the `ravel-markdown` backend.

I have added a bit of text to `org-ravel.org` to explain this and how to add commands to the init file. 

Thanks for your comment.
