### ISSUE TITLE
inline R code translated to wrong quote

### ISSUE THREAD

**Issue by fkgruber** [chasberry/orgmode-accessories#28]
Hi
I tried the latest ox-ravel and it appears that inline code is translated with the wrong quote.
For example in org-mode I use
Rows: src_R{dim(nrow(mtcars))}

but the resulting Rmd looks like:
Rows: ‘r dim(nrow(mtcars)) ‘
instead of
Rows:  \`r dim(nrow(mtcars)) \`

and therefore, gets ignored by rmarkdown.

Do you see this as well?
thanks
FKG

**Comment by fkgruber** [comment]
I fixed this by changing the function:
```
  (defun org-ravel-inline-md (ravel r-headers-attr src-code)
    "Wrap SRC-CODE as inline rmarkdown code"
    (format "@@html:`r  %s `@@" src-code))
```

**Comment by chasberry** [comment]
Thanks. I used your fix.
