### ISSUE TITLE
No code block headers in exported Rmd

### ISSUE THREAD

**Issue by pjaml** [chasberry/orgmode-accessories#30]
I've installed the most recent ox-ravel.el from the `org-9-plus` branch. When I export to R markdown, any R source code blocks in my org file become an indented block without any headers in the resulting Rmd file. For example,

```Org
#+title: Test

Here is some text.

#+begin_src R
a <- rnorm(100)
summary(a)
#+end_src

More text.
```
exports to
```RMarkdown
---
# YAML header created by ox-ravel
title: Test
author: pjaml
---
Here is some text.

    a <- rnorm(100)
    summary(a)

More text.
```
I was expecting the code block to be wrapped with backticks (i.e. \```{r}), but it isn't.

When I tried using an org inline src block, I was getting the error: `cond: Symbol’s function definition is void: org-babel-expand-body:R`. But I was able to fix this by adding `(require 'ob-R)` near the top of `ox-ravel.el`. So now (as expected)

```Org
Here is some inline code src_R{1+3}.
```
exports to
```RMarkdown
Here is some inline code `r 1+3 `.
```
But multiline code blocks still don't get wrapped in backticks. Is there something I'm missing? Thanks!

**Comment by chasberry** [comment]
That looks like what would happen if babel did not recognize the language. i.e. if you had `#+begin_src Rx`.

Be sure to enable R language blocks. See `16.9 Languages` in the Org Mode manual.

I'll add a note about this in `ox-ravel.org`.

Thanks.

**Comment by pjaml** [comment]
Thanks for responding! I'm not sure that's the issue though. I'm using Doom Emacs, and I think R blocks are enabled by default. I've never had any issues executing R code blocks and getting the output. Also, when I export to Github markdown via pandoc, the output has correctly labeled R code blocks.

To be sure, I explicitly added R to `org-babel-load-languages` and I'm still having the same issue.

**Comment by chasberry** [comment]
Hmm.

Please, try eval-ing this:

    #+begin_src emacs-lisp
      (org-ravel-block-md "ABC" nil nil nil "a <- 1")
    #+end_src
    
and see if you get this:

    #+RESULTS:
    : ```{r}
    : #| label: ABC
    : a <- 1
    : ```

And maybe try to retype the `#+begin_src R` by hand to be sure there aren't any hidden characters confusing matters.

**Comment by pjaml** [comment]
That works, I got the correct results. 

Actually, I'm able to fix the issue when I add `:exports results` to the src block header. This isn't what I was expecting though --- shouldn't `:exports code` (which is the default) output the code to Rmd? I would expect `:exports results` to evaluate the block and put the results in the exported Rmd file. Maybe I just misunderstood the documentation, is this how it's supposed to behave?

I'm glad I've sort of got it working at least!

**Comment by chasberry** [comment]
I'm glad you got it sorted out.

It is not quite intuitive admittedly. What happens under the hood is ravel _executes_ the src block according to its own rules. Those rules format the body and wrap it in the right code chunk markup.

So, it needs to execute. So setting `:eval no` will prevent ravel from acting.

But the `:exports results` is not needed. In fact, an explicit `:exports code` is revised to `:exports results` by `org-ravel-rewrap`. This block:

    #+begin_src R  :exports code
       a <- 1
    #+end_src       
yields

     ```{r}
     a <- 1
     ```

**Comment by pjaml** [comment]
Hmm, that doesn't work for me --- using an explicit `:exports code` results in a block without a header as before. 
Using `:exports results` could create some difficulties if I needed to export to multiple formats, since it'll behave in the opposite way for all other exporters.

Also, when using `:exports both`, is this the intended behavior?

```
#+begin_src R :exports both
5 + 5
#+end_src
```
results in
```
5 + 5

```{r}
5 + 5
`​``
```

**Comment by chasberry** [comment]
You should have just this

    ```{r}
    5 + 5
    ```
You already confirmed that `org-ravel-block-md` returns the expected result, so the problem must be further upstream. The next place to check is `org-ravel-rewrap`. Try to replicate this. 

Export this using ravel-markdown:
    
    #+name: blk1
    #+begin_src R :exports both
      5 + 5
    #+end_src
    
    
    #+begin_src emacs-lisp :exports results :results pp
      (save-excursion
        (org-babel-goto-named-src-block "blk1")
        (org-ravel-rewrap (org-babel-get-src-block-info) nil nil))
    
    #+end_src
    
 The result I get is:

    ---
    # YAML header created by ox-ravel
    author: Charles Berry
    ---
    ```{r}
    #| label: blk1
    5 + 5
    ```
    
        ((:results . "replace")
         (:wrap . "EXPORT RAVEL")
         (:exports . "results")
         (:engine)
         (:colname-names)
         (:rowname-names)
         (:result-params "replace")
         (:result-type . value)
         (:results-arg . "replace")
         (:exports-arg . "both")
         (:tangle . "no")
         (:hlines . "no")
         (:noweb . "no")
         (:cache . "no")
         (:session . "none"))
    
 If you get something else we have a hint about where to look next. If the export utterly fails, try to put the cursor on `save-excursion` and type `C-c C-c` and you should get a results block with the contents of the printed list.

Also, please report what `M-x version` and `M-x org-version` say.    

FWIW, I have tried both current org 9.7-pre and older 9.5.5 and get the same results. I use emacs 28.2.

**Comment by pjaml** [comment]
Thanks again for walking me through this! My result is slightly different:

```RMarkdown
---
# YAML header created by ox-ravel
title: Test
author: pjaml
---
    5 + 5

    ```{r}
    #| label: blk1
    5 + 5
    ```

    ((:results . "replace")
     (:wrap . "EXPORT RAVEL")
     (:exports . "results")
     (:engine)
     (:colname-names)
     (:rowname-names)
     (:result-params "replace")
     (:result-type . value)
     (:results-arg . "replace")
     (:exports-arg . "code")
     (:tangle . "no")
     (:hlines . "no")
     (:noweb . "no")
     (:cache . "no")
     (:session . "none"))
```
So I'm getting 2 code blocks exported, one without the proper Rmarkdown formatting and one with. And then the value of `:exports-arg` is `"code"`.

I'm also using Emacs 28.2, and my org mode version is 9.6.1.

**Comment by chasberry** [comment]
I am sorry, but there is a bug in the code I gave you, so before trying to go further I wonder if you can run this instead and see if the `:exports-arg` value is the still `code`:


    #+begin_src emacs-lisp :exports results :results pp
      (save-excursion
        (org-babel-goto-named-src-block "blk2a")
        (let ((org-ravel-run nil))
          (org-ravel-rewrap (org-babel-get-src-block-info) nil nil)))
    #+end_src 
    
    
    #+name: blk2a
    #+begin_src R :exports both
      5 + 5
    #+end_src
    
If it is, can you also put the cursor in the `blk2a` src block and type `C-c C-v C-i`?

You should have a buffer like this:

    Name: blk2a
    Lang: R
    Properties:
        :header-args    nil
        :header-args:R  nil
    Header Arguments:
        :cache          no
        :exports        both
        :hlines         no
        :noweb          no
        :results        replace
        :session        none
        :tangle         no

If not, that tells us that the issue likely rests in `org-babel-get-src-block-info`.

Thanks.

**Comment by pjaml** [comment]
I tried the updated code, and this time I did get `"both"` for `:exports-arg`. After running `C-c C-v C-i` the buffer I got is identical to yours.

**Comment by chasberry** [comment]
This is becoming a challenge...

Maybe best to start from scratch. Start emacs from a command or terminal window with `-q`. Then copy this into the *scratch* buffer:

    (add-to-list 'load-path "<path to ox-ravel.el>")
    
    (add-to-list 'load-path (expand-file-name "<path to ess-site.el>"))
    
     (org-babel-do-load-languages
       'org-babel-load-languages
       '((R . t)
         (emacs-lisp . t)))
    
    (require 'ox-ravel)
    (require 'ox-md)
    (require 'ess-site)
    

Modify the `<path...>` bits for your setup. Then evaluate the buffer (`M-x eval-buffer RET`).  

Or create such a file with those contents and use it as the init file.

Create an org buffer  (e.g. `C-x b orgbuf RET M-x org-mode RET`) and paste this into it:

    #+author: somebody
    
    #+name: test-blk
    #+begin_src R
      a <- 1
      a + 1
    #+end_src
    
Type `M-: (org-ravel-export-to-buffer 'ravel-markdown) RET`    and compare to this:

    ---
    # YAML header created by ox-ravel
    author: somebody
    ---
    ```{r}
    #| label: test-blk
    a <- 1
    a + 1
    ```
    
If it matches then the issue is in your initializations.

If it doesn't match, try downloading `ox-ravel.org` and creating a fresh `ox-ravel.el` and repeat the prior steps.

If it still doesn't match, maybe a fresh install of org will fix it. 

Apart from that I have no ideas. I haven't heard of anybody having similar problems. So I am afraid you would need to take a deep dive into debugging to sort matters out. Alternatively, you might construct a hack by advising `org-export-format-code-default` to discard its result when confronting an `R` or `ravel` `src-block`.
