### ISSUE TITLE
Getting odd .md/.Rmd results (html tags inserted in output)

### ISSUE THREAD

**Issue by jwhendy** [chasberry/orgmode-accessories#6]
I returned to work on a presentation I'd started perhaps a month ago and am getting strange `.md` and `.Rmd` output. I don't use `ox-ravel` that frequently, but I believe my process is the same. Here's a minimal config:

```
(add-to-list 'load-path "~/.elisp/org.git/lisp/")
(add-to-list 'load-path "~/.elisp/org.git/contrib/lisp")
(add-to-list 'load-path "~/.elisp/ravel/")
(add-to-list 'load-path "~/.elisp/ess/lisp/")

(require 'ox-ravel)
(require 'ess-site)

;; setup babel languages
(org-babel-do-load-languages
 'org-babel-load-languages
 '((R . t)))
```

Also:
```
M-x version
Org-mode version 8.3.3 (release_8.3.3-470-g3142d1 @ ~/.elisp/org.git/lisp/)

[~/.elisp/ravel] $ git show
commit 6e97186a0c96a2abb3474bfabacb95c92e1aa4e0
Merge: 87f03f0 c95ec9a
```

I'm using `slidify-example.org` file, unmodified. Here's the top of the output after running the `new-deck` code block, followed by `C-c C-e C-s m m/r`:

**./test-deck/my.md**
```
<div class="MD">
&#x2014;
title       : Ravel for slidify
subtitle    : a minimal slidy deck

[snip]

widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
&#x2014;

</div>
```

**./test-deck/my.Rmd**
```
<div class="MD">
&#x2014;
title       : Ravel for slidify
subtitle    : a minimal slidy deck

[snip]

widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
&#x2014;

</div>
```

If I export the whole file (no `C-s` to restrict to subtree), I get this:

**./slidify-example.Rmd**
```
</div>
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#orgheadline1">1. Setup for test-deck</a></li>
<li><a href="#tds-headline">2. test-deck slides</a>
<ul>
<li><a href="#orgheadline2">2.1. Setup notes</a></li>
<li><a href="#orgheadline3">2.2. Square root of 2</a></li>
<li><a href="#orgheadline4">2.3. Square root of 3</a></li>
<li><a href="#orgheadline5">2.4. Mauna Whau Plot - code</a></li>
<li><a href="#orgheadline6">2.5. Mauna Whau Plot - Displayed</a></li>
</ul>
</li>
<li><a href="#orgheadline7">3. Run it</a></li>
</ul>
</div>
</div>
```

Am I doing something incorrectly? To my knowledge, this is the process I've used in the past (export to `.Rmd`), but this has never happened before! Thanks for taking a look.

**Comment by chasberry** [comment]
My bad. After the export block syntax changed to

    #+BEGIN_EXPORT MD
    ...
    #+END_EXPORT
in 
    commit 54318add34f09ff39d3fd034a4c1a89f60fd8759

I changed all the places in the elisp code where this would matter.

But I forgot about ```slidify-example.org```. So the exporter treated the block as a `special` block, which is not the way it needs to be.

I just pushed a commit that fixes the example. You will need to convert your export blocks. If you only have one at the top of a file you can hand edit it to look like the example above. OTOH, if you have a bunch of them, see find the function ```org-repair-export-blocks``` listed in NEWS in

 http://orgmode.org/cgit.cgi/org-mode.git/plain/etc/ORG-NEWS

and run that.

**Comment by jwhendy** [comment]
Ahhh... I should have caught that, as I was aware of the change. I posted an issue for `ox-reveal`, as this change broke that momentarily (quickly fixed). It works now that I've updated the block syntax. Thanks!
