### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ybkamaleri** [chasberry/orgmode-accessories#9]

**Comment by chasberry** [comment]
Do internal links even work in the latex backend (no ravel)? A quick trial suggests they do not. I get 
`user-error: Unable to resolve link: "plot1"`

This pull request: https://github.com/chasberry/orgmode-accessories/pull/8

might be relevant to your issue. If a src block has a `:results graphics` header and a name, it might be possible to provide a target to which an internal link will match.

I will be away the rest of March and won't be able to look at what this entails until sometime in April.

As far as captions, that is easier. Define something like this

```
#+BEGIN_SRC emacs-lisp 
(defun org-ravel-get-knitr-caption (&optional prefix)
  "Find the caption and format as knitr caption. If PREFIX is nil use `fig.cap=' as the prefix of the result."
  (concat (or prefix "fig.cap=") "\""
          (mapconcat
           'substring-no-properties 
           (org-export-get-caption (org-element-at-point)) "")
       "\""
       ))
#+END_SRC
```

and run it before exporting. Add `#+headers: :ravel (org-ravel-get-knit-caption)` just before the `#+BEGIN_SRC R` line and you should get

```
<<plot1, fig.cap="Plot testing", echo=FALSE>>=
x <- 1:30
plot(x)
@ %def
```

as the result.

Thanks for your feedback.
